name: continuous-integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: 'continuous-integration'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        magento-version: [ '2.4.6' ]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 19
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Cache Magento Repository
        id: cache-magento
        uses: actions/cache@v2
        with:
          path: magento
          key: magento-${{ matrix.magento-version }}

      - name: Create Magento Project
        if: steps.cache-magento.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: magento/magento2
          ref: ${{ matrix.magento-version }}
          path: magento
          fetch-depth: 0

      - name: Add config.php file to Magento
        run: cp .github/_fixtures/config.php.dist "$GITHUB_WORKSPACE/magento/app/etc/config.php"

      - run: pnpm i
      - run: pnpm lint

      - run: pnpm test
        env:
          MAGEFRONT_TEST_MAGENTO_ROOT: ${{ github.workspace }}/magento
