name: continuous-integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
      MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.11.0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:2
          php-version: 8.1
          coverage: none

      - name: Setup Magento Repository Credentials
        run: |
          composer global config http-basic.repo.magento.com "${MAGENTO_MARKETPLACE_USERNAME}" "${MAGENTO_MARKETPLACE_PASSWORD}";

      - name: Define Magento ROOT for tests
        run: echo "Set Magento root to $WORKSPACE"
        env:
          MAGEFRONT_TEST_MAGENTO_ROOT: ${{ github.workspace }}/magento

      - name: Create Magento Project
        run: |
          composer create-project --ignore-platform-reqs --repository-url=https://repo.magento.com/ magento/project-community-edition "$GITHUB_WORKSPACE/magento";
          cp tests/_fixtures/config.php.dist "$GITHUB_WORKSPACE/magento/app/etc/config.php";

      - run: pnpm i

      - run: pnpm test
        env:
          MAGEFRONT_TEST_MAGENTO_ROOT: ${{ github.workspace }}/magento
