name: documentation

on:
  push:
    tags: [ '*' ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
