name: documentation

on:
  push:
    tags: [ '*' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 19
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - run: pnpm i
      - run: pnpm run build
        env:
          SVELTEKIT_BASE_URL: /magefront

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'sites/magefront/build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
