name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.11.0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:2
          php-version: 8.1
          coverage: none

      - name: Setup Magento Repository Credentials
        run: |
          composer global config http-basic.repo.magento.com "${MAGENTO_MARKETPLACE_USERNAME}" "${MAGENTO_MARKETPLACE_PASSWORD}";

      - run: pnpm i
      - run: pnpm test
